### ISSUE TITLE
Review dependency licenses

### ISSUE THREAD

**Issue by blackspherefollower** [metafetish/buttplug-csharp#100]
We need to check the licences of the libraries pulled into the project. We should also deal with the attributions whilst we're at it.

**Comment by qdot** [comment]
The license part is mostly done already, see LICENSE file in the root directory. That covers us and everything that was in the library a couple of weeks ago. Just forgot to check that on newtonsoft. :(

If you want to double check it, that'd be awesome.

For attributions, that's a good question, as I'll need to make that a project-wide policy.

**Comment by qdot** [comment]
Just close this out when you've looked over the doc and think it's ok.

**Comment by blackspherefollower** [comment]
Looks like there are a few missing:
https://www.nuget.org/packages/CommandLineParser/
https://www.nuget.org/packages/JetBrains.Annotations/
https://www.nuget.org/packages/OpenCover/
SharpRaven

Fortunately they're all MIT
