### ISSUE TITLE
SingleMotorVibrateCmd turns off vibrator when speed is 1

### ISSUE THREAD

**Issue by blackspherefollower** [metafetish/buttplug-csharp#177]
At max, the vibrator shuts off instead of running at max.

**Comment by FredTungsten** [comment]
Cause is the 65536 here: https://github.com/metafetish/buttplug-csharp/blob/master/Buttplug.Server.Managers.XInputGamepadManager/XInputGamepadDevice.cs#L35

Should be ushort.MaxValue instead

**Comment by qdot** [comment]
Fixed via #177.
