### ISSUE TITLE
Kiiroo Onyx 2

### ISSUE THREAD

**Issue by supangel** [metafetish/buttplug-csharp#320]
Please add support for Kiiroo Onyx 2. Thanks

**Comment by qdot** [comment]
We'll see what we can do! I only have a Pearl 2 right now, but hopefully we can get things working for that and the Onyx 2 protocol will be similar. I'll let you know when that's done if you're interested in helping test. :)

**Comment by qdot** [comment]
Managed to get some beginning identifier info for the Onyx 2, see metafetish/stpihkal#13
