### ISSUE TITLE
New Lovense name LVS-Lush39

### ISSUE THREAD

**Issue by Mkorho** [metafetish/buttplug-csharp#400]
Lush39 is not in the code list for supported devices.
Can it be wildcard like LVS-Lush* ? 

2018-05-18 14:08:15.5471|TRACE|UWPBluetoothManager|BLE device found: LVS-Lush39

**Comment by qdot** [comment]
Thanks for filing this! We're working on wildcarding right now in #392.

A new release should be out any time now (I'm just writing tests at the moment), but if you'd like, there's a beta build at https://ci.appveyor.com/api/buildjobs/73loa4lwhrj6982u/artifacts/Buttplug-Release-0.2.1.666-installer.exe that should work for you.

**Comment by Mkorho** [comment]
Works Great.
And good work.
