### ISSUE TITLE
Figure out Windows Firewall rule setup for Websocket server

### ISSUE THREAD

**Issue by qdot** [metafetish/buttplug-csharp#98]
The Websocket Server needs to be able to detect that it can use the port its asking for. If it can't, it should guide the user on setting that up.

**Comment by blackspherefollower** [comment]
I appear to have inadvertently done whatever was necessary to get the firewall popup working in my C# client refactoring branch: https://github.com/blackspherefollower/buttplug-csharp/tree/csharp-client
