### ISSUE TITLE
Remove Newtonsoft JSON.Schema library

### ISSUE THREAD

**Issue by blackspherefollower** [metafetish/buttplug-csharp#99]
Turns out the licensing around Newtonsoft licensing involves a usage limit. Let's find something better, with a BSD or MIT license.

**Comment by qdot** [comment]
Note that this is JUST for the Schema library, which is AGPL (and therefore a problem anyways, I should've caught that. :( ). The JSON library is MIT licensed, and it's already in the license file, so that's fine.
